#!/bin/sh /etc/rc.common

START=99
STOP=20

USE_PROCD=1

start_service() {
    l2cm_libuci &
    logger -s "start_service"
}

reload_service() {
    restart
}

stop_service() {
    logger -s "stop_service"
}

service_running() {
    logger -s "service_running"
}

service_triggers()
{
    logger -s "service_triggers"
}

restart() {
    stop
    sleep 1
    start
}

shutdown() {
    logger -s "shutdown"
}
